### PR TITLE
Use GitHub actions to autogenerate docs

### PR DESCRIPTION
**Pull request by snmishra**
I've set it up to autogenerate docs in `gh-pages` branch. Current docs available at https://snmishra.github.io/django-categories/

If you want to host the generated docs on GitHub pages, you'll need to create the file `.nojekyll` in the `gh-pages` branch. It should be a one time action.

### CODE REVIEW

**Comment by mazulo** [comment]
Hey @snmishra thank you for that. I'm thinking about forking this repo and get your changes into it so that I can push to PyPI something like django-categories2 since this repo doesn't seems to be maintained anymore. Dozens of PRs and issues just pilling up.

**Comment by mazulo** [comment]
Also I will try to follow these steps to generate the docs on gh pages 

> If you want to host the generated docs on GitHub pages, you'll need to create the file `.nojekyll` in the `gh-pages` branch. It should be a one time action.

**Comment by coordt** [comment]
@mazulo Would you like to be added as a maintainer of this project? I am unable to give it the attention it needs.

**Comment by mazulo** [comment]
Hey @coordt I can imagine how it can be (been there). Now I'm having some free time that I can use to contribute again to the community. So we can either do it (add me as member/maintainer) or apply the project to https://jazzband.co/

**Comment by coordt** [comment]
@mazulo It is now a part of Jazzband. Thank you for the suggestion.

**Comment by mazulo** [comment]
@coordt I'm more than happy it was helpful! Have a nice day and thank you for your hard work on this tool! I'm using and loving it!

**Pull request merged**
