### PR TITLE
Add API endpoint (through Django REST framework) + documentation

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
I have rewritten the code, so now it is very efficient - all categories with related objects count are returned in one query. I have spent a day researching how to do that, so I think it is worth including in the project, so noone has to undergo that.

The tests are broken in master branch the same way.

**Comment by epicserve** [comment]
@PetrDlouhy,

Doing a quick look at your code ... I think it looks good. However, I don't really want to add the Django Rest Framework as a dependency that would need to be maintained, when you could easily add the routes and endpoints in your project that uses DRF. I would merge this in if you wanted to just add some example code to the documentation that anyone could use to copy and paste into their project. I think how you use the endpoint could be very opinioned as well and depending on the project you might want to customize it according to the project's requirements.

**Comment by PetrDlouhy** [comment]
@epicserve @coordt 
I have update this to current master and I am willing to make high quality patch from this. I will add tests, docs, some more features (related object cumulative counts etc.) I have now only in my project.

I think, that this code is worth to be shared and maintained by community. It is not just trivial DRF implementation, there is work and optimization I spent time on. Also having same API implementation for categories across applications can increase interoperability between them.

I don't consider adding this as example code in docs good option at all. It will only result in code copying rather than sharing and improving it together.

Please reconsider if you really don't want this to be part of `django-categories`. If you don't think so, I will respect that and create separate application `django-categories-api` with this code.

**Comment by PetrDlouhy** [comment]
I have created separate project for the API: [django-categories-api](https://github.com/PetrDlouhy/django-categories-api)

I would be glad if I could add some note about that project into README file of `django-categories`. But maybe it would be needed to fix the documentation (https://github.com/jazzband/django-categories/issues/115) and clean up the README file a bit first.

**Comment by PetrDlouhy** [comment]
I have added note about django-categories-api to the docs myself. I think this could be closed now.

**Pull request closed without merging**
